export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
